//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishCourse_Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public int id_UserCourse { get; set; }
        public Nullable<int> id_User { get; set; }
        public Nullable<int> id_Course { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
